name: "Get latest blog posts"

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Get posts
              uses: gautamkrishnar/blog-post-workflow@v1
              with:
                  max_post_count: "3"
                  feed_list: "https://uncenter.dev/feed.xml"
                  skip_commit: true

            - name: Commit changes
              uses: EndBug/add-and-commit@v9
              with:
                  message: "chore: update blog posts list"
                  default_author: github_actions
